# Generated by Django 2.2.3 on 2019-11-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='power_trace_request_id',
            field=models.IntegerField(null=True),
        ),
    ]
