# Generated by Django 2.2.2 on 2019-07-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listproperties',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='admin@admin.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
