# Generated by Django 2.2.2 on 2019-07-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190705_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='angle',
            field=models.DecimalField(decimal_places=6, default=90, max_digits=9),
        ),
    ]
