# Generated by Django 2.2.3 on 2019-11-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_forgetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scout')),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserList')),
            ],
            options={
                'db_table': 'scouts_user_lists',
            },
        ),
        migrations.DeleteModel(
            name='ScoutsProperty',
        ),
    ]
