# Generated by Django 2.2.3 on 2019-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userlocation_angle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_acct', models.CharField(max_length=255, null=True)),
                ('gma_tag', models.CharField(max_length=255, null=True)),
                ('property_address', models.CharField(max_length=255, null=True)),
                ('owner_name', models.CharField(max_length=255, null=True)),
                ('owner_address', models.CharField(max_length=255, null=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('lon', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'property_infos',
            },
        ),
    ]
