# Generated by Django 2.2.3 on 2019-07-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_propertyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertynotes',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PropertyInfo'),
        ),
        migrations.AlterField(
            model_name='propertyphotos',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PropertyInfo'),
        ),
        migrations.AlterField(
            model_name='userownershipusage',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PropertyInfo'),
        ),
        migrations.AlterField(
            model_name='visitedproperties',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PropertyInfo'),
        ),
    ]
