# Generated by Django 2.2.3 on 2019-12-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity_id',
            field=models.IntegerField(null=True),
        ),
    ]
