# Generated by Django 2.2.3 on 2019-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190716_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytags',
            name='property',
            field=models.ManyToManyField(to='api.PropertyInfo'),
        ),
    ]
