# Generated by Django 2.2.3 on 2019-07-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_propertytags_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytags',
            name='property',
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='property_tags',
            field=models.ManyToManyField(to='api.PropertyTags'),
        ),
    ]
