# Generated by Django 2.2.3 on 2019-12-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_activitylog_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
