# Generated by Django 2.2.3 on 2019-12-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activitylog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upgrade',
            field=models.BooleanField(default=False),
        ),
    ]
