# Generated by Django 2.2.3 on 2019-07-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190717_0701'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdriver',
            table='user_drivers',
        ),
    ]
