# Generated by Django 2.2.2 on 2019-08-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190717_1025'),
        ('api', '0004_auto_20190806_1106'),
    ]

    operations = [
    ]
