# Generated by Django 2.2.3 on 2019-12-20 03:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetNeighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField(null=True)),
                ('neighborhood', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Property')),
            ],
            options={
                'db_table': 'get_neighborhoods',
            },
        ),
    ]
