# Generated by Django 2.2.3 on 2019-12-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_getneighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='getneighborhood',
            name='owner_status',
            field=models.CharField(default='fetching', max_length=50),
        ),
    ]
