# Generated by Django 2.2.3 on 2019-12-23 04:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_getneighborhood_owner_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getneighborhood',
            old_name='neighborhood',
            new_name='ownership_info',
        ),
        migrations.RenameField(
            model_name='getneighborhood',
            old_name='request_id',
            new_name='ownership_info_request_id',
        ),
        migrations.AddField(
            model_name='getneighborhood',
            name='power_trace',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='getneighborhood',
            name='power_trace_request_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='getneighborhood',
            name='power_trace_status',
            field=models.CharField(default='fetching', max_length=50),
        ),
        migrations.AddField(
            model_name='getneighborhood',
            name='status',
            field=models.CharField(default='fetching', max_length=50),
        ),
    ]
