# Generated by Django 2.2.2 on 2019-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190806_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperties',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listproperties',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
    ]
