# Generated by Django 2.2.4 on 2019-08-08 06:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190806_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_acct', models.CharField(max_length=255, null=True)),
                ('gma_tag', models.CharField(max_length=255, null=True)),
                ('property_address', models.CharField(max_length=255, null=True)),
                ('owner_info', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('google_place_id', models.CharField(max_length=255, null=True, unique=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('lon', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_tags', models.ManyToManyField(to='api.PropertyTags')),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.AlterField(
            model_name='propertynotes',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        ),
        migrations.AlterField(
            model_name='propertyphotos',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        ),
        migrations.AlterField(
            model_name='userownershipusage',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        ),
        migrations.AlterField(
            model_name='visitedproperties',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        ),
        migrations.DeleteModel(
            name='PropertyInfo',
        ),
    ]
