# Generated by Django 2.2.4 on 2019-08-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190808_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_tags',
            field=models.ManyToManyField(blank=True, to='api.PropertyTags'),
        ),
    ]
