# Generated by Django 2.2.3 on 2019-12-23 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_upgradeprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentplan',
            table='payment_plans',
        ),
        migrations.AlterModelTable(
            name='plans',
            table='plans',
        ),
        migrations.AlterModelTable(
            name='upgradeprofile',
            table='upgrade_profiles',
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_coin', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PaymentPlan')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Property')),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
    ]
