# Generated by Django 2.2.3 on 2019-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invitations',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
