# Generated by Django 2.2.3 on 2019-12-23 09:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191223_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_coin', models.IntegerField(null=True)),
                ('transaction_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PaymentPlan')),
                ('upgrade_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UpgradeProfile')),
            ],
        ),
    ]
