# Generated by Django 2.2.3 on 2019-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_upgradehistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upgradehistory',
            table='upgrade_histories',
        ),
    ]
