# Generated by Django 2.2.3 on 2019-12-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191223_0404'),
        ('api', '0016_auto_20191223_0927'),
    ]

    operations = [
    ]
