# Generated by Django 2.2.3 on 2019-08-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_scout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
