# Generated by Django 2.2.3 on 2019-12-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20191223_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='payment_plan_coin',
            field=models.IntegerField(default=0),
        ),
    ]
