# Generated by Django 2.2.3 on 2019-08-30 08:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_scoutslistproperty'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='listproperties',
        #     name='owner_info',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserList')),
        # ),
        # migrations.AddField(
        #     model_name='listproperties',
        #     name='property',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        # ),
    ]
