# Generated by Django 2.2.3 on 2019-12-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191224_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgradehistory',
            name='payment_plan',
        ),
        migrations.AddField(
            model_name='upgradehistory',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Plans'),
            preserve_default=False,
        ),
    ]
