# Generated by Django 2.2.3 on 2019-08-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190830_0841'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='listproperties',
        #     name='property',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        # ),
    ]
