# Generated by Django 2.2.3 on 2019-12-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191224_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scout',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='payment_plan_coin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_coin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_coin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='upgradehistory',
            name='transaction_coin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='upgradeprofile',
            name='coin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
