# Generated by Django 2.2.3 on 2019-12-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20191226_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='getneighborhood',
            name='neighbor_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
