# Generated by Django 2.2.3 on 2019-08-30 08:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190830_0843'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='listproperties',
        #     old_name='list',
        #     new_name='user_list',
        # ),
        # migrations.AlterField(
        #     model_name='listproperties',
        #     name='owner_info',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        # ),
    ]
