# Generated by Django 2.2.3 on 2019-12-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_getneighborhood_neighbor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getneighborhood',
            name='owner_status',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='getneighborhood',
            name='power_trace_status',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
