# Generated by Django 2.2.3 on 2019-08-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190830_0851'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='listproperties',
        #     name='property',
        # ),
    ]
