# Generated by Django 2.2.3 on 2019-08-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_listproperties_property'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='listproperties',
        #     name='property',
        #     field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        # ),
    ]
