# Generated by Django 2.2.3 on 2019-08-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_listproperties_property'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='listproperties',
        #     name='owner_info',
        # ),
    ]
