# Generated by Django 2.2.3 on 2019-12-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191230_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='getneighborhood',
            name='is_owner_info_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='getneighborhood',
            name='is_power_trace_requested',
            field=models.BooleanField(default=False),
        ),
    ]
