# Generated by Django 2.2.3 on 2019-12-31 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20191231_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='getneighborhood',
            name='requested_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
