# Generated by Django 2.2.3 on 2019-08-30 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_listproperties_owner_info'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='listproperties',
        #     name='property',
        # ),
        # migrations.AddField(
        #     model_name='listproperties',
        #     name='owner_info',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        # ),
    ]
