# Generated by Django 2.2.3 on 2019-12-31 08:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_getneighborhood_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getneighborhood',
            name='ownership_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='getneighborhood',
            name='power_trace',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
