# Generated by Django 2.2.3 on 2019-08-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190830_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproperties',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listproperties',
            name='owner_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
