# Generated by Django 2.2.3 on 2019-12-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20191231_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='getneighborhood',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='getneighborhood',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
    ]
