# Generated by Django 2.2.3 on 2019-08-30 11:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190830_1111'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='listproperties',
        #     old_name='user_list',
        #     new_name='list',
        # ),
        # migrations.AlterField(
        #     model_name='listproperties',
        #     name='owner_info',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserList')),
        # ),
    ]
