# Generated by Django 2.2.3 on 2019-08-30 11:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190830_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listproperties',
            old_name='user_list',
            new_name='list',
        ),
        migrations.AlterField(
            model_name='listproperties',
            name='owner_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserList')),
        ),
        # migrations.CreateModel(
        #     name='ScoutsListProperty',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('list_properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ListProperties')),
        #         ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scout')),
        #     ],
        #     options={
        #         'db_table': 'scouts_list_properties',
        #     },
        # ),
    ]
