# Generated by Django 2.2.3 on 2020-01-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_indexes'),
        ('api', '0029_auto_20200102_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification')),
            ],
            options={
                'db_table': 'notifications',
            },
            bases=('notifications.notification',),
        ),
    ]
