# Generated by Django 2.2.3 on 2020-01-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_mailwizardinfo_mailwizardsubstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailwizardinfo',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
