# Generated by Django 2.2.3 on 2020-01-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
