# Generated by Django 2.2.3 on 2020-01-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_mailwizardinfo_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailwizardinfo',
            name='subs_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MailWizardSubsType'),
        ),
    ]
