# Generated by Django 2.2.3 on 2020-01-09 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200108_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50, null=True)),
                ('card_number', models.CharField(max_length=50, null=True)),
                ('card_code', models.CharField(max_length=5, null=True)),
                ('exp_date', models.CharField(max_length=7, null=True)),
                ('is_save', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_card_info',
            },
        ),
    ]
