# Generated by Django 2.2.3 on 2020-01-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_delete_notification'),
        ('api', '0032_auto_20200108_1203'),
    ]

    operations = [
    ]
