# Generated by Django 2.2.3 on 2020-01-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_merge_20200109_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Plans'),
            preserve_default=False,
        ),
    ]
