# Generated by Django 2.2.3 on 2020-01-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_paymentplan_plan'),
        ('api', '0033_billingcardinfo'),
    ]

    operations = [
    ]
