# Generated by Django 2.2.3 on 2020-01-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_20200109_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='getneighborhood',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='getneighborhood',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='getneighborhood',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='getneighborhood',
            name='zip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
