# Generated by Django 2.2.3 on 2020-01-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200110_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getneighborhood',
            name='city',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='getneighborhood',
            name='state',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='getneighborhood',
            name='street',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='getneighborhood',
            name='zip',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
