# Generated by Django 2.2.3 on 2019-09-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190903_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='lon',
            new_name='longitude',
        ),
        # migrations.CreateModel(
        #     name='ScoutsListProperty',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('list_properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ListProperties')),
        #         ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scout')),
        #     ],
        #     options={
        #         'db_table': 'scouts_list_properties',
        #     },
        # ),
    ]
