# Generated by Django 2.2.3 on 2020-01-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200110_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailwizardinfo',
            name='neighbor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GetNeighborhood'),
        ),
    ]
