# Generated by Django 2.2.3 on 2019-09-05 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20190904_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scout',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # migrations.CreateModel(
        #     name='ScoutsListProperty',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('list_properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ListProperties')),
        #         ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scout')),
        #     ],
        #     options={
        #         'db_table': 'scouts_list_properties',
        #     },
        # ),
    ]
