# Generated by Django 2.2.3 on 2020-01-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_mailwizardinfo_neighbor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='description',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='image',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
