# Generated by Django 2.2.3 on 2020-01-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20200117_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailwizardinfo',
            name='mail_count_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailwizardinfo',
            name='mail_counter',
            field=models.IntegerField(default=0),
        ),
    ]
