# Generated by Django 2.2.3 on 2020-01-20 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200120_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailWizardCeleryTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default=0, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mail_wizard_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MailWizardInfo')),
            ],
            options={
                'db_table': 'mail_wizard_celery_tasks',
            },
        ),
    ]
