# Generated by Django 2.2.3 on 2020-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_mailwizardcelerytasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFirebase',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=50, null=True)),
                ('device_version', models.CharField(max_length=50, null=True)),
                ('firebase_token', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_firebase',
            },
        ),
    ]
