# Generated by Django 2.2.3 on 2020-01-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_userfirebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfirebase',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
