# Generated by Django 2.2.3 on 2019-09-24 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20190911_0538'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ScoutsListProperty',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('list_properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ListProperties')),
        #         ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scout')),
        #     ],
        #     options={
        #         'db_table': 'scouts_list_properties',
        #     },
        # ),
        migrations.CreateModel(
            name='AssignMemberToList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserList')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assign_member_to_list',
            },
        ),
    ]
