# Generated by Django 2.2.3 on 2020-01-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_userfirebase_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='fetch_lat_lng',
            field=models.BooleanField(default=True),
        ),
    ]
