# Generated by Django 2.2.3 on 2020-01-31 09:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_userlist_fetch_lat_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailwizardinfo',
            name='request_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='MailWizardUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('company_name', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('phone_no', models.CharField(max_length=25, null=True)),
                ('address_street', models.TextField(null=True)),
                ('address_city', models.CharField(max_length=255, null=True)),
                ('address_state', models.CharField(max_length=50, null=True)),
                ('address_zip', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mail_wizard_user_info',
            },
        ),
    ]
