# Generated by Django 2.2.3 on 2020-02-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20200131_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_thumb',
            field=models.TextField(default=None, null=True),
        ),
    ]
