# Generated by Django 2.2.3 on 2019-09-27 04:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_scoutslistproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listproperties',
            name='tag',
        ),
        migrations.AddField(
            model_name='listproperties',
            name='property_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_tags',
        ),
        migrations.AddField(
            model_name='property',
            name='property_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        # migrations.CreateModel(
        #     name='ScoutsListProperty',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('list_properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ListProperties')),
        #         ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scout')),
        #     ],
        #     options={
        #         'db_table': 'scouts_list_properties',
        #     },
        # ),
    ]
