# Generated by Django 2.2.3 on 2019-10-09 06:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20191003_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutsProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Property')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scout')),
            ],
            options={
                'db_table': 'scouts_properties',
            },
        ),
        migrations.RemoveField(
            model_name='scoutslistproperty',
            name='property',
        ),
        migrations.RemoveField(
            model_name='scoutslistproperty',
            name='scout',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_address',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='google_place_id',
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='user_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.UserList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='zip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gma_tag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.DeleteModel(
            name='ListProperties',
        ),
        migrations.DeleteModel(
            name='ScoutsListProperty',
        ),
    ]
