# Generated by Django 2.2.3 on 2020-03-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20200212_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradeprofile',
            name='expire_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
