# Generated by Django 2.2.3 on 2020-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_upgradeprofile_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradeprofile',
            name='expire_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
