# Generated by Django 2.2.3 on 2019-10-09 06:18


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20191009_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutsProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Property')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scout')),
            ],
            options={
                'db_table': 'scouts_properties',
            },
        ),
        migrations.RenameField(
            model_name='scoutsproperty',
            old_name='scout',
            new_name='scouts',
        ),
    ]
