# Generated by Django 2.2.3 on 2020-03-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20200304_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
