# Generated by Django 2.2.3 on 2019-10-22 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20191009_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point_latitude', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
                ('start_point_longitude', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
                ('end_point_latitude', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
                ('end_point_longitude', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('polylines', models.TextField(null=True)),
                ('length', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='HistoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.History')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Property')),
            ],
            options={
                'db_table': 'history_details',
            },
        ),
    ]
