# Generated by Django 2.2.3 on 2020-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_appleuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleuserid',
            name='user_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
