# Generated by Django 2.2.3 on 2020-03-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20200325_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appleuserid',
            name='id',
        ),
        migrations.AlterField(
            model_name='appleuserid',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
