# Generated by Django 2.2.3 on 2020-03-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200325_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleuserid',
            name='jwt_token',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
