# Generated by Django 2.2.3 on 2020-04-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_appleuserid_jwt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
