# Generated by Django 2.2.3 on 2020-04-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_userlist_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='is_default',
        ),
    ]
