# Generated by Django 2.2.3 on 2020-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_userlist_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
