# Generated by Django 2.2.3 on 2020-07-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20200707_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliateuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
