# Generated by Django 2.2.3 on 2020-07-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_affliateuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
