# Generated by Django 2.2.3 on 2020-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, null=True)),
                ('value', models.IntegerField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Setting',
            },
        ),
    ]
