# Generated by Django 2.2.3 on 2020-07-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
