# Generated by Django 2.2.3 on 2020-07-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200707_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
