# Generated by Django 2.2.3 on 2020-07-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20200707_0753'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='setting',
            table='setting',
        ),
    ]
