# Generated by Django 2.2.3 on 2020-07-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20200707_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponuser',
            name='commission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='couponuser',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
