# Generated by Django 2.2.3 on 2020-07-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20200707_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliateuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='couponuser',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
