# Generated by Django 2.2.3 on 2020-07-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20200707_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponuser',
            name='plan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Plans'),
        ),
    ]
