# Generated by Django 2.2.3 on 2020-07-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_couponuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliateuser',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Affiliate User'),
        ),
    ]
