# Generated by Django 2.2.3 on 2020-07-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20200709_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliateuser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
