# Generated by Django 2.2.3 on 2020-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20200710_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliateuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
