# Generated by Django 2.2.3 on 2020-07-15 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20200714_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliateuser',
            name='code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Length has to be 8', regex='^.{8}$')]),
        ),
    ]
