# Generated by Django 2.2.3 on 2020-07-15 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20200715_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliateuser',
            name='code',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Length has to be 6', regex='^.{6}$')]),
        ),
    ]
