# Generated by Django 2.2.3 on 2020-07-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20200715_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliateuser',
            name='commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='affliateuser',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
    ]
