# Generated by Django 2.2.3 on 2020-07-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20200717_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliateuser',
            name='commission',
            field=models.FloatField(default=0.0, verbose_name='Commission (%)'),
        ),
        migrations.AlterField(
            model_name='affliateuser',
            name='discount',
            field=models.FloatField(default=0.0, verbose_name='Discount (%)'),
        ),
    ]
