# Generated by Django 2.2.3 on 2020-07-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20200722_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponuser',
            name='affiliate_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
