# Generated by Django 2.2.3 on 2020-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_couponuser_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailwizarduserinfo',
            name='agent_license',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailwizarduserinfo',
            name='cover_photo',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mailwizarduserinfo',
            name='logo',
            field=models.TextField(default=None, null=True),
        ),
    ]
